# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SumNote-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SumNote-iOS
  pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
  pod 'KakaoSDKAuth'  # 사용자 인증
  pod 'KakaoSDKUser'  # 카카오 로그인, 사용자 관리
  pod 'Kingfisher' # url to image

  target 'SumNote-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SumNote-iOSUITests' do
    # Pods for testing
  end

end
